### PR TITLE
Add voice sections.

### PR DESCRIPTION
**Pull request by SmilerRyan**
Added the seperators, removed the prefixes, and changed the default voice to "Select a voice".

### CODE REVIEW

**Comment by Weilbyte** [comment]
Hi, thank you for the PR. Could you make two changes:

1. Check if voice is selected before making a submission
2. Add more obvious separation to the sections by bolding section title and adding an empty row

**Comment by SmilerRyan** [comment]
The validation and the separation changes have been completed.

image

image

**Comment by Weilbyte** [comment]
Thank you :)

**Comment by Vultades** [comment]
I'm Italian I can translate if you want

**Pull request merged**
